name: This is a test

on: push

jobs:
  echo-hello:
    run-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "Hello , world"
  echo-goodbye:
    run-on: ubuntu-latest
    steps:
      - name: Failed Stop
        run: |
          echo "I will fail"
          exit 1
      - name: Say goodbye
        run: echo "Goodbye!" #This will not get executed
