name: 04 - Using action

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 04-using-actions/react-app
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
      - name: Install Dependencies
        run: npm ci
      - name: Run Unit test
        run: npm run test

    # 0. Checkout the code from the repository
    # 1. Install deps of out react applications from node module "npm install"
    # 2. Execute LINT test and build testing
