name: 05 - Event Filters and Activity in CI / CD

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running whenever a PR is opened ir synchronized on local machine and the branch is main"
