name: 09 - Using Expresion and If

on:
  push:
  workflow_dispatch:
    inputs:
      debug:
        description: Debug event , false as default
        type: boolean
        default: false

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: "[debug] Print start-up"
        if: ${{inputs.debug}}
        run: |
          echo "Triggered by ${{github.event_name}}"
          echo 'Branch: ${{github.ref}}'
          echo 'Commit SHA key: ${{github.sha}}'
          echo 'Runner OS ${{runner.os}}'
      - name: "[debug] Triggered Print from main"
        if: ${{inputs.debug && github.ref == 'refs/heads/main'}}
        run: echo "I was triggered from main "
      - name: Greeting for testing
        run: echo "Hello, world "
