name: This is a test

on: workflow_dispatch

jobs:
  echo-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "Hello, world"

  echo-goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: Failed Stop
        run: |
          echo "I will fail"
          exit 1
      - name: Say goodbye
        run: echo "Goodbye!" # This won't execute due to failure above
