name: 20 - Dockerfile Action Example Ping URL

on:
  workflow_dispatch:
    inputs:
      url:
        type: string
        description: The URL to ping
        default: "https://google.com"
      target-branch:
        type: string
        description: The branch where the PR will be created
        default: "update-url"
      working_directory:
        type: string
        description: The working directory of the project to check the URL ping
        default: "./15-caching/react-app"

jobs:
  ping-url:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Ping URL
        uses: ./.github/actions/docker-ping-url
        with:
          url: ${{ inputs.url }}
